import { expect, test, describe, beforeAll } from "bun:test";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildBoneIndex, allocBoneTransforms, forwardKinematics, type AnnyModel,
} from "../../src/anny/index.js";
import {
  landmarksToPoseDeltas, MP, type WorldLandmark,
} from "../../src/mediapipe/index.js";
import { loadFixtureModel } from "../_helpers/model.js";
import { verifyPoseAlignment } from "./verify.js";

const here = dirname(fileURLToPath(import.meta.url));
const FIXTURES = resolve(here, "fixtures");

/** Synthetic A-pose landmarks (subject facing camera, arms slightly out). */
function aPose(): WorldLandmark[] {
  const lm: WorldLandmark[] = Array.from({ length: 33 }, () => ({ x: 0, y: 0, z: 0, visibility: 1 }));
  const set = (i: number, x: number, y: number, z: number) => {
    lm[i] = { x, y, z, visibility: 1 };
  };
  set(MP.LEFT_HIP,  +0.10, 0.00, 0.00);
  set(MP.RIGHT_HIP, -0.10, 0.00, 0.00);
  set(MP.LEFT_SHOULDER,  +0.18, -0.50, 0.00);
  set(MP.RIGHT_SHOULDER, -0.18, -0.50, 0.00);
  set(MP.LEFT_ELBOW,  +0.40, -0.30, 0.00);
  set(MP.RIGHT_ELBOW, -0.40, -0.30, 0.00);
  set(MP.LEFT_WRIST,  +0.55, -0.05, 0.00);
  set(MP.RIGHT_WRIST, -0.55, -0.05, 0.00);
  set(MP.LEFT_INDEX,  +0.60, +0.05, 0.00);
  set(MP.RIGHT_INDEX, -0.60, +0.05, 0.00);
  set(MP.LEFT_KNEE,  +0.10, +0.45, 0.00);
  set(MP.RIGHT_KNEE, -0.10, +0.45, 0.00);
  set(MP.LEFT_ANKLE,  +0.10, +0.90, 0.00);
  set(MP.RIGHT_ANKLE, -0.10, +0.90, 0.00);
  set(MP.LEFT_FOOT_INDEX,  +0.10, +0.93, -0.10);
  set(MP.RIGHT_FOOT_INDEX, -0.10, +0.93, -0.10);
  set(MP.LEFT_EAR,   +0.08, -0.70, 0.00);
  set(MP.RIGHT_EAR,  -0.08, -0.70, 0.00);
  set(MP.LEFT_EYE,   +0.04, -0.73, -0.05);
  set(MP.RIGHT_EYE,  -0.04, -0.73, -0.05);
  set(MP.MOUTH_LEFT, +0.03, -0.65, -0.05);
  set(MP.MOUTH_RIGHT,-0.03, -0.65, -0.05);
  return lm;
}

function runDriver(
  model: AnnyModel,
  boneIndex: Map<string, number>,
  lm: WorldLandmark[],
  opts: { visibilityMin?: number } = {},
) {
  const deltas = landmarksToPoseDeltas({ pose: lm, ...opts }, model, boneIndex);
  const boneXforms = allocBoneTransforms(model.boneCount);
  forwardKinematics(model, deltas, boneXforms);
  return boneXforms;
}

describe("MediaPipe → Anny driver — angular parity", () => {
  let model: AnnyModel;
  let boneIndex: Map<string, number>;

  beforeAll(async () => {
    model = await loadFixtureModel();
    boneIndex = buildBoneIndex(model);
  });

  test("synthetic A-pose: every driven segment within 1° of its MP target", () => {
    const lm = aPose();
    const boneXforms = runDriver(model, boneIndex, lm);
    const { meanErrDeg, segments } = verifyPoseAlignment(model, boneIndex, boneXforms, lm);
    // Driver-produced rotations should reconstruct the MP target essentially exactly
    // on synthetic input (no landmark noise). 1° leaves headroom for f32 rounding.
    for (const s of segments) {
      expect(s.errDeg, `${s.seg} err=${s.errDeg.toFixed(2)}°`).toBeLessThan(1);
    }
    expect(meanErrDeg).toBeLessThan(0.5);
  });

  /**
   * Captured-from-real-video fixture parity. Fixtures are generated by
   * `tools/capture_landmarks.ts` (Playwright + MediaPipe heavy) and committed
   * under `tests/mediapipe/fixtures/`. If a fixture isn't present yet, its
   * test is skipped — slot stays in the suite as a placeholder.
   *
   * Thresholds are per-fixture and tight: they sit ~1.5–3× above the
   * driver's current measured mean (see `tools/measure_fixture_errors.ts`).
   * Tight enough to catch any axis flip / convention regression; loose
   * enough to absorb MediaPipe model-version noise on the existing clips.
   *
   * Driver setting matches the demo: `visibilityMin: 0.2` so half-occluded
   * limbs still drive (otherwise the boxer's far arm falls through and the
   * "error" we measure is mostly "bone left at rest", not driver math).
   */
  const fixtureCases: Array<{ name: string; file: string; maxMeanDeg: number }> = [
    { name: "boxer",  file: "boxer_landmarks.json",  maxMeanDeg: 4.0 },
    { name: "dancer", file: "dancer_landmarks.json", maxMeanDeg: 1.0 },
  ];

  for (const { name, file, maxMeanDeg } of fixtureCases) {
    const path = resolve(FIXTURES, file);
    const exists = Bun.file(path).size > 0;
    const it = exists ? test : test.skip;

    it(`captured ${name} fixture: mean angular error under ${maxMeanDeg}°`, async () => {
      const data: { frames: { worldLandmarks: WorldLandmark[] }[] } = JSON.parse(
        await Bun.file(path).text(),
      );
      const errors: number[] = [];
      for (const frame of data.frames) {
        const boneXforms = runDriver(model, boneIndex, frame.worldLandmarks, { visibilityMin: 0.2 });
        const { meanErrDeg } = verifyPoseAlignment(model, boneIndex, boneXforms, frame.worldLandmarks);
        errors.push(meanErrDeg);
      }
      const overall = errors.reduce((a, b) => a + b, 0) / errors.length;
      expect(overall, `${name}: overall mean ${overall.toFixed(2)}° (limit ${maxMeanDeg}°)`)
        .toBeLessThan(maxMeanDeg);
    });
  }
});
